### PR TITLE
Improvement on sem_ctl + psreg 

### PR DESCRIPTION
**Pull request by pkotamnives**
- increase wait time in `sem_ctl `from 0.5 s to 5 s
- detect if a semaphore 1 is already taken in `psmon_reg` so that `psreg` won't crash the CLI in case that a semaphore 1 is taken.

### CODE REVIEW

**Comment by pwittich** [comment]
can you just do this cleanly from a new branch rather than from `missing semaphores`, or rebase `missing_semaphores` on master?

**Comment by pkotamnives** [comment]
@pwittich , would you prefer using acquireI2CSemaphore added in SensorControl just line what is [here](https://github.com/apollo-lhc/cm_mcu/blob/9e857dbfc0f63bcaacc9c7ef438004951c6fa1fd/projects/cm_mcu/commands/I2CCommands.c#L43-L58) to break the infinite sem Take loop or the current version is good enough?

**Comment by pkotamnives** [comment]
> can you just do this cleanly from a new branch rather than from `missing semaphores`, or rebase `missing_semaphores` on master?

sure. I can rebase it from the master after the review is done? there is an option "Rebase and merge."

**Comment by pwittich** [comment]
> > can you just do this cleanly from a new branch rather than from `missing semaphores`, or rebase `missing_semaphores` on master?
> 
> sure. I can rebase it from the master after the review is done? there is an option "Rebase and merge."

I guess you merged changes from master in. we should definitely do a squash and merge, not a rebase and merge.
In the future please delete a branch after you merge it and start a new branch for every new task.

**Comment by pwittich** [comment]
> @pwittich , would you prefer using acquireI2CSemaphore added in SensorControl just like what is [here](https://github.com/apollo-lhc/cm_mcu/blob/9e857dbfc0f63bcaacc9c7ef438004951c6fa1fd/projects/cm_mcu/commands/I2CCommands.c#L43-L58) to break the infinite sem Take loop or the current version is good enough?

it is probably nice to try to use a function to do this, in case we have to change it in the future.

**Comment by pkotamnives** [comment]
@pwittich , is it a good idea to move `acquireI2CSemaphore` and `getSemaphore` to Semaphore.c ? my question is that `acquireI2CSemaphore` is currently declared as a `static int` and I am not sure if it will still work as expected if it is declared as `int` in Semaphore?

**Comment by pwittich** [comment]
> @pwittich , is it a good idea to move `acquireI2CSemaphore` and `getSemaphore` to Semaphore.c ? my question is that `acquireI2CSemaphore` is currently declared as a `static int` and I am not sure if it will still work as expected if it is declared as `int` in Semaphore?

just make it non-static

**Pull request merged**
